name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-


      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
      - run: cd build
      - run: ls
      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
  deployToItch:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: itch
      deployment: false
    env:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download webgl Artifact
        uses: actions/download-artifact@v4
        with:
          name: Build
          path: build
      - run: ls
      - name: Get butler
        run: wget https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default -O butler-linux-amd64.zip
      - name: unzip
        run: unzip butler-linux-amd64.zip
      - run: chmod +x butler
      - run: ./butler login
      - run: ls
      - run: ./butler push build im-xura/test:HTML
