name: Upload to itch

on: [push, pull_request]

jobs:
  deployToItch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get butler
        run: curl --output butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
      - run: ls
      - name: unzip
        run: unzip ./butler.zip
      - run: chmod +x ./butler/butler
