name: Upload to itch

on: [push, pull_request]

jobs:
  deployToItch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get butler
        run: wget https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default -O
      - run: ls
      - name: unzip
        run: file butler-linux-amd64.zip
      - run: chmod +x butler
